package:
  name: kdb
  version: "3.6.20180614"

build:
  number: 0

source:
  url: https://cl.ly/2r1v1v3h0l41/download/l64.zip				# [linux64]
  fn: l64.zip									# [linux64]
  sha256: 28c26f796a7fa9267a3061598fe0e1e34208b4deb5932db42adc78f9d2a74481	# [linux64]
  url: https://cl.ly/1c2r0V3G3B3y/download/w64.zip				# [win64]
  fn: w64.zip									# [win64]
  sha256: 68e802d7d7dc8b1f95f4976cb3a34b2593134ca35a168d517d9f031a8ecd0c89	# [win64]
  url: https://cl.ly/1l381Q1G041F/download/m64.zip				# [osx]
  fn: m64.zip									# [osx]
  sha256: 36c85349c6fc5bdd152dfd53f5e03c3d00a225557c85ce8acd2b2bba56dafbe2	# [osx]

# neuters unable to find libm.so.6...
requirements:
  build:
    - {{ compiler('c') }}
  run:
    - python

about:
  home: https://kx.com
  license: Commercial
  summary: kdb+
